name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "stage" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: 'Login to GitHub Container Registry'
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}}

    - name: Build the Docker image
      env:
        IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest
      run: |
        docker build . --tag $IMAGE_NAME
        docker push $IMAGE_NAME
